// Download the Noto web fonts Patha bundles, and write fonts/fonts.css.
// Run once when changing fonts: node scripts/fetch-fonts.mjs
//
// The app never contacts a font service at runtime: the files are served
// from the site itself. Each script subset has its own unicode-range, so a
// browser only downloads the files for the scripts on the page.
// Noto fonts are licensed under the SIL Open Font License (fonts/OFL.txt).

import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';

const out = fileURLToPath(new URL('../fonts/', import.meta.url));
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/140.0 Safari/537.36';

// [Google Fonts family, subsets to keep]
const FAMILIES = [
  ['Noto Serif', ['latin', 'latin-ext', 'cyrillic', 'cyrillic-ext', 'greek', 'vietnamese']],
  ['Noto Serif Devanagari', ['devanagari']],
  ['Noto Serif Bengali', ['bengali']],
  ['Noto Serif Gurmukhi', ['gurmukhi']],
  ['Noto Serif Gujarati', ['gujarati']],
  ['Noto Serif Tamil', ['tamil']],
  ['Noto Serif Telugu', ['telugu']],
  ['Noto Serif Kannada', ['kannada']],
  ['Noto Serif Malayalam', ['malayalam']],
  ['Noto Serif Sinhala', ['sinhala']],
  ['Noto Naskh Arabic', ['arabic']],
  ['Noto Serif Hebrew', ['hebrew']],
  ['Noto Serif Thai', ['thai']],
];

const css = [
  '/* Generated by scripts/fetch-fonts.mjs. Noto fonts: SIL Open Font License 1.1 (see OFL.txt). */',
  '/* One family name, split by script with unicode-range: browsers fetch only what a page uses. */',
];
await mkdir(out, { recursive: true });

for (const [family, keep] of FAMILIES) {
  const url = `https://fonts.googleapis.com/css2?family=${encodeURIComponent(family).replace(/%20/g, '+')}:wght@400..700&display=swap`;
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${family}: HTTP ${res.status}`);
  const text = await res.text();
  const blocks = [...text.matchAll(/\/\*\s*([\w-]+)\s*\*\/\s*@font-face\s*{([^}]*)}/g)];
  for (const [, subset, body] of blocks) {
    if (!keep.includes(subset)) continue;
    const src = body.match(/url\((https:[^)]+\.woff2)\)/)?.[1];
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1];
    const weight = body.match(/font-weight:\s*([^;]+);/)?.[1] ?? '400 700';
    if (!src || !range) continue;
    const file = `${family.toLowerCase().replace(/\s+/g, '-')}-${subset}.woff2`;
    const data = Buffer.from(await (await fetch(src, { headers: { 'User-Agent': UA } })).arrayBuffer());
    await writeFile(`${out}${file}`, data);
    css.push(
      `/* ${family}, ${subset} */`,
      '@font-face {',
      "  font-family: 'Patha Serif';",
      '  font-style: normal;',
      `  font-weight: ${weight};`,
      '  font-display: swap;',
      `  src: url('${file}') format('woff2');`,
      `  unicode-range: ${range};`,
      '}',
    );
    console.log(`${file}  ${(data.length / 1024).toFixed(0)} KB`);
  }
}

await writeFile(`${out}fonts.css`, `${css.join('\n')}\n`);
console.log('wrote fonts/fonts.css');
